PROMPT_BRANCH='\033[0;35m'
PROMPT_STAGED='\033[0;32m'
PROMPT_MODIFIED='\033[0;31m'
PROMPT_UNTRACKED='\033[0;33m'
PROMPT_PATH='\033[0;37m'
PROMPT_ERROR='\033[0;31m'
PROMPT_CHAR_COLOR='\033[0m'

PROMPT_BRANCH_CHOICES=($COL_RES $COL_PIN $COL_CYA $COL_GRY)
PROMPT_UNTRACKED_CHOICES=($COL_YEL $COL_CYA)
PROMPT_PATH_CHOICES=($COL_RES $COL_GRY $COL_CYA)
PROMPT_CHAR_COLOR_CHOICES=($COL_RES $COL_CYA $COL_GRY)
