PROMPT_BRANCH='\033[38;5;127m'
PROMPT_STAGED='\033[38;5;34m'
PROMPT_MODIFIED='\033[38;5;124m'
PROMPT_UNTRACKED='\033[38;5;100m'
PROMPT_PATH='\033[38;5;20m'
PROMPT_ERROR='\033[38;5;160m'
PROMPT_CHAR_COLOR='\033[0m'

PROMPT_BRANCH_CHOICES=($COL_RES $COL_BLA_BLU4 $COL_BLA_CYA1 $COL_BLA_CYA2 $COL_BLA_PIN2 $COL_BLA_PIN3 $COL_BLA_PIN4 )
PROMPT_STAGED_CHOICES=($COL_BLA_GRE2 $COL_BLA_GRE3 $COL_BLA_GRE4)
PROMPT_MODIFIED_CHOICES=($COL_BLA_RED2 $COL_BLA_RED3 $COL_BLA_RED4)
PROMPT_UNTRACKED_CHOICES=($COL_BLA_YEL1 $COL_BLA_YEL2 $COL_BLA_YEL3 $COL_BLA_CYA1 $COL_BLA_CYA2 $COL_BLA_CYA3)
PROMPT_PATH_CHOICES=($COL_RES $COL_BLA_WHI1 $COL_BLA_WHI2 $COL_BLA_BLU1 $COL_BLA_BLU4 $COL_BLU)
PROMPT_ERROR_CHOICES=($COL_BLA_RED3 $COL_BLA_RED4 $COL_RED)
PROMPT_CHAR_COLOR_CHOICES=($COL_RES $COL_BLA_WHI1 $COL_BLA_BLU2 $COL_BLA_BLU4 $COL_BLA_PIN1 $COL_BLA_PIN2 \
                           $COL_BLA_CYA1 $COL_BLA_CYA2)

STDOUT_HIGHLIGHT=$COL_BLU; export STDOUT_HIGHLIGHT
