PROMPT_BRANCH='\033[38;5;201m'
PROMPT_STAGED='\033[38;5;40m'
PROMPT_MODIFIED='\033[38;5;196m'
PROMPT_UNTRACKED='\033[38;5;184m'
PROMPT_PATH='\033[38;5;147m'
PROMPT_ERROR='\033[38;5;196m'
PROMPT_CHAR_COLOR='\033[0m'

PROMPT_BRANCH_CHOICES=($COL_RES $COL_BLA_CYA1 $COL_BLA_CYA2 $COL_BLA_CYA3 $COL_BLA_CYA4 $COL_BLA_PIN3 \
                       $COL_BLA_PIN4 $COL_PIN $COL_PIN_WHI1 )
PROMPT_STAGED_CHOICES=($COL_BLA_GRE2 $COL_BLA_GRE3 $COL_BLA_GRE4)
PROMPT_MODIFIED_CHOICES=($COL_BLA_RED3 $COL_BLA_RED4 $COL_RED)
PROMPT_UNTRACKED_CHOICES=($COL_BLA_YEL2 $COL_BLA_YEL3 $COL_BLA_YEL4 $COL_BLA_CYA3 $COL_BLA_CYA4 $COL_CYA)
PROMPT_PATH_CHOICES=($COL_BLA_WHI2 $COL_BLA_WHI3 $COL_WHI $COL_BLU_WHI2 $COL_BLU_WHI3 $COL_CYA $COL_YEL $COL_YEL_WHI2)
PROMPT_ERROR_CHOICES=($COL_BLA_RED3 $COL_BLA_RED4 $COL_RED)
PROMPT_CHAR_COLOR_CHOICES=($COL_RES $COL_BLA_WHI2 $COL_BLA_WHI3 $COL_BLU_WHI2 $COL_PIN_WHI2 $COL_CYA $COL_CYA_WHI3)

STDOUT_HIGHLIGHT=$COL_BLA_CYA3       ; export STDOUT_HIGHLIGHT
STDOUT_OK=$COL_GRE                   ; export STDOUT_OK
STDOUT_NOTOK=$COL_RED                ; export STDOUT_NOTOK
STDOUT_WARNING=$COL_PIN_WHI1         ; export STDOUT_WARNING
STDOUT_DIRECTORY=$COL_BLU_CYA2       ; export STDOUT_DIRECTORY
STDOUT_LINK=$COL_PIN_WHI1            ; export STDOUT_LINK
STDOUT_BINARY_EXECUTABLE=$COL_RED    ; export STDOUT_BINARY_EXECUTABLE
STDOUT_TEXT_EXECUTABLE=$COL_GRE      ; export STDOUT_TEXT_EXECUTABLE
STDOUT_EMPTY_OR_MISSING=$COL_BLA_YEL3; export STDOUT_EMPTY_OR_MISSING

STDOUT_DIFF_MODIFIED="$STDOUT_HIGHLIGHT\033[1m"; export STDOUT_DIFF_MODIFIED
STDOUT_DIFF_ADDED="$STDOUT_OK\033[1m"          ; export STDOUT_DIFF_ADDED
STDOUT_DIFF_REMOVED="$STDOUT_NOTOK\033[1m"     ; export STDOUT_DIFF_REMOVED
